# Build Stage
FROM golang:1.26.4-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o seeder ./cmd/seeder

# Runtime Stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/seeder .
CMD ["./seeder"]