import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
  stages: [
    { duration: '30s', target: 50 }, // Ramp up to 50 concurrent virtual users
    { duration: '2m', target: 100 }, // Maintain heavy load at 100 users
    { duration: '30s', target: 0 }, // Cooldown scale back down
  ],
};

// Replace this placeholder value with a real user UUID generated by your seeder script
const SAMPLE_USER_UUID = '478f1836-f576-4ecb-950b-19be7d83eb61';

export default function () {
  let randSelector = Math.random();

  if (randSelector < 0.7) {
    // 70% Read Path traffic split
    let res = http.get(`http://localhost:8080/users/${SAMPLE_USER_UUID}`);
    check(res, { 'read status was 200': (r) => r.status === 200 });
  } else {
    // 30% Write Path traffic split
    let res = http.post(
      `http://localhost:8080/events?user_id=${SAMPLE_USER_UUID}&type=LOAD_TEST_HIT`,
    );
    check(res, { 'write status was 201': (r) => r.status === 201 });
  }
  sleep(0.01); // Short pause to manage resource scheduling efficiently
}
